import type { Group } from "../types/groups.js";

export const groups: Group[] = [
  {
    id: "grp-1",
    membersIds: ["pax001", "pax008"],
    size: 2,
    totalWeight: 124,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-2",
    membersIds: ["pax002", "pax048", "pax094"],
    size: 3,
    totalWeight: 299,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-3",
    membersIds: ["pax003", "pax050"],
    size: 2,
    totalWeight: 154,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-4",
    membersIds: ["pax004", "pax041", "pax013"],
    size: 3,
    totalWeight: 228,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-5",
    membersIds: ["pax005", "pax099", "pax090", "pax038", "pax092", "pax045"],
    size: 6,
    totalWeight: 515,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: true,
    hasFemaleMuslim: true,
  },
  {
    id: "grp-6",
    membersIds: [
      "pax006",
      "pax028",
      "pax036",
      "pax072",
      "pax056",
      "pax020",
      "pax064",
      "pax095",
    ],
    size: 8,
    totalWeight: 618,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-7",
    membersIds: ["pax007", "pax055", "pax083"],
    size: 3,
    totalWeight: 233,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: true,
    hasFemaleMuslim: true,
  },
  {
    id: "grp-8",
    membersIds: ["pax009", "pax058", "pax019", "pax054"],
    size: 4,
    totalWeight: 314,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: true,
    hasFemaleMuslim: true,
  },
  {
    id: "grp-9",
    membersIds: ["pax010", "pax091", "pax030", "pax011"],
    size: 4,
    totalWeight: 297,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: true,
    hasFemaleMuslim: true,
  },
  {
    id: "grp-10",
    membersIds: ["pax012", "pax087", "pax068"],
    size: 3,
    totalWeight: 231,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-11",
    membersIds: ["pax014", "pax085", "pax060", "pax100"],
    size: 4,
    totalWeight: 362,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-12",
    membersIds: ["pax015", "pax040", "pax093", "pax069"],
    size: 4,
    totalWeight: 292,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-13",
    membersIds: ["pax016", "pax021", "pax081"],
    size: 3,
    totalWeight: 239,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-14",
    membersIds: ["pax017", "pax075", "pax062", "pax025", "pax098"],
    size: 5,
    totalWeight: 340,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-15",
    membersIds: ["pax018", "pax096", "pax057", "pax029", "pax066"],
    size: 5,
    totalWeight: 357,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-16",
    membersIds: ["pax022", "pax089", "pax043"],
    size: 3,
    totalWeight: 201,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-17",
    membersIds: ["pax023", "pax061", "pax071", "pax024"],
    size: 4,
    totalWeight: 296,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-18",
    membersIds: ["pax026", "pax078"],
    size: 2,
    totalWeight: 167,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-19",
    membersIds: ["pax027"],
    size: 1,
    totalWeight: 60,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-20",
    membersIds: ["pax031", "pax076", "pax034", "pax074"],
    size: 4,
    totalWeight: 240,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-21",
    membersIds: ["pax032", "pax065"],
    size: 2,
    totalWeight: 137,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: true,
    hasFemaleMuslim: true,
  },
  {
    id: "grp-22",
    membersIds: ["pax033", "pax046"],
    size: 2,
    totalWeight: 130,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: true,
    hasFemaleMuslim: true,
  },
  {
    id: "grp-23",
    membersIds: ["pax035", "pax059"],
    size: 2,
    totalWeight: 206,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: true,
    hasFemaleMuslim: true,
  },
  {
    id: "grp-24",
    membersIds: ["pax037", "pax097", "pax084", "pax079", "pax063"],
    size: 5,
    totalWeight: 388,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-25",
    membersIds: ["pax039", "pax070"],
    size: 2,
    totalWeight: 209,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-26",
    membersIds: ["pax042", "pax080"],
    size: 2,
    totalWeight: 130,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-27",
    membersIds: ["pax044"],
    size: 1,
    totalWeight: 50,
    hasWCHR: false,
    hasUMNR: true,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-28",
    membersIds: ["pax047"],
    size: 1,
    totalWeight: 58,
    hasWCHR: false,
    hasUMNR: true,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-29",
    membersIds: ["pax049", "pax082", "pax052"],
    size: 3,
    totalWeight: 263,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-30",
    membersIds: ["pax051"],
    size: 1,
    totalWeight: 95,
    hasWCHR: false,
    hasUMNR: true,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-31",
    membersIds: ["pax053"],
    size: 1,
    totalWeight: 91,
    hasWCHR: true,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-32",
    membersIds: ["pax067"],
    size: 1,
    totalWeight: 56,
    hasWCHR: false,
    hasUMNR: true,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-33",
    membersIds: ["pax073"],
    size: 1,
    totalWeight: 73,
    hasWCHR: false,
    hasUMNR: true,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-34",
    membersIds: ["pax077", "pax088"],
    size: 2,
    totalWeight: 125,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
  {
    id: "grp-35",
    membersIds: ["pax086"],
    size: 1,
    totalWeight: 84,
    hasWCHR: false,
    hasUMNR: false,
    hasMuslim: false,
    hasFemaleMuslim: false,
  },
];
